### ISSUE TITLE
Remove sidebar fix

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#11]
Remove the sidebar fix from `custom.css` which the Product Details configuration disappear :|

```
/* FIX FOR SIDEBAR */

section.container > div > .col-md-3 {
    display: none;
}
section.container > div > .col-md-9 {
    width: 100%;
}
```

It does horrible injuries to Product Details:
![screenshot-kloud51 com 2015-11-24 14-57-09](https://cloud.githubusercontent.com/assets/591113/11364904/81b54ba6-92bc-11e5-979d-c873707c5904.png)

Where is should be actually:
![screenshot-kloud51 com 2015-11-24 15-01-25](https://cloud.githubusercontent.com/assets/591113/11364923/9635f26a-92bc-11e5-9180-ecb6c420e9c8.png)

**Comment by AmirSavand** [comment]
I'll do it with jQuery then

**Comment by AmirSavand** [comment]
Fixed with this code and removed CSS code.

``` javascript
if ($('#btnShowSidebar').length) {
    $("section.container > div > .col-md-3").remove();
    $("section.container > div > .col-md-9").css('width', '100%');
}
```

**Comment by Alir3z4** [comment]
@amirm3hdi Thing is still happening but somewhere else:

![screenshot-kloud51 com 2015-11-26 13-06-49](https://cloud.githubusercontent.com/assets/591113/11419127/c856246c-943e-11e5-9718-74f7d0b2dde4.png)

**Comment by AmirSavand** [comment]
Fixed
